#!/bin/bash

# Get the Python file name from the environment variable
py_file="$PYFILE"

# Check if the file exists
if [ -f "$py_file" ]; then
    # Run the Python script
    python3 "$py_file"
else
    echo "Error: Python file '$py_file' not found."
fi

