#!/bin/bash

# Get the Python code from the environment variable
py_code="$PYCODE"

# Create a temporary Python file
tmp_file=$(mktemp)
echo "$py_code" > "$tmp_file"

# Run the Python script
python3 "$tmp_file"

# Clean up the temporary file
rm "$tmp_file"

